version: "3.8"
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5000 upload:app --reload
    environment:
      - FLASK_APP=upload.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    volumes:
      - ./:/root